<<<<<<< Updated upstream
# Generated by Django 4.2.20 on 2025-04-22 21:10
=======
# Generated by Django 4.2.20 on 2025-04-21 18:29
>>>>>>> Stashed changes

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="BulletinPost",
            fields=[
                (
                    "post_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("post_type", models.CharField(max_length=100)),
                ("visibility", models.CharField(max_length=50)),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
