<<<<<<< HEAD
# Generated by Django 4.2.20 on 2025-05-02 23:51
=======
# Generated by Django 4.2.20 on 2025-05-10 21:01
>>>>>>> 2853bf3805e39ed850dac0c989affcba4e0192cf

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        ('neighborly_bulletin', '0001_initial'),
=======
        ("neighborly_bulletin", "0001_initial"),
>>>>>>> 2853bf3805e39ed850dac0c989affcba4e0192cf
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name='bulletinitem',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_posts', to=settings.AUTH_USER_MODEL),
=======
            model_name="bulletinitem",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bulletin_posts",
                to=settings.AUTH_USER_MODEL,
                to_field="user_id",
            ),
>>>>>>> 2853bf3805e39ed850dac0c989affcba4e0192cf
        ),
    ]
