# Generated by Django 4.2.20 on 2025-04-28 21:37

from django.db import migrations, models
import django.utils.timezone
import neighborly_bulletin.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BulletinItem',
            fields=[
                ('post_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('post_type', models.CharField(max_length=100)),
                ('visibility', models.CharField(default='public', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('images', models.ImageField(blank=True, null=True, upload_to=neighborly_bulletin.models.bulletin_image_upload_path)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('date_updated', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('location', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='BulletinPost',
        ),
    ]
