# Generated by Django 4.2.20 on 2025-04-28 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0002_bulletinitem_delete_bulletinpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinitem',
            name='post_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
