# Generated by Django 4.2.20 on 2025-04-29 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0003_alter_bulletinitem_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinitem',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
