# Generated by Django 4.2.20 on 2025-04-29 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('neighborly_bulletin', '0004_alter_bulletinitem_images'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bulletinitem',
            name='user_id',
        ),
        migrations.AddField(
            model_name='bulletinitem',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bulletin_posts', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
