# Generated by Django 4.2.20 on 2025-04-29 04:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0006_rename_user_bulletinitem_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinitem',
            old_name='user_id',
            new_name='user',
        ),
    ]
