# Generated by Django 4.2.20 on 2025-05-01 00:58

from django.db import migrations, models
import neighborly_bulletin.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0007_rename_user_id_bulletinitem_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bulletinitem',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=neighborly_bulletin.models.bulletin_image_upload_path),
        ),
    ]
