# Generated by Django 4.2.20 on 2025-05-01 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_bulletin', '0008_alter_bulletinitem_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bulletinitem',
            old_name='images',
            new_name='image',
        ),
    ]
