# Generated by Django 4.2.20 on 2025-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("service_provider", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
                ("available", models.BooleanField(default=True)),
                ("waitlist", models.JSONField(blank=True, default=list)),
                ("earliest_availability", models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceSignUp",
            fields=[
                ("signup_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "service_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neighborly_services.serviceitem",
                    ),
                ),
            ],
        ),
    ]
