# Generated by Django 4.2.20 on 2025-03-24 22:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ServiceItem",
            fields=[
                ("service_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("service_provider", models.IntegerField()),
                ("location", models.CharField(max_length=255)),
                ("date_posted", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="ServiceStatus",
            fields=[
                ("status_id", models.AutoField(primary_key=True, serialize=False)),
                ("service_id", models.IntegerField()),
                ("available", models.BooleanField(default=True)),
                ("current_user", models.IntegerField(blank=True, null=True)),
                (
                    "waitlist",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.IntegerField(),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                ("earliest_availability", models.DateField(blank=True, null=True)),
            ],
        ),
    ]
