# Generated by Django 4.2.20 on 2025-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='service_provider',
            field=models.CharField(max_length=255),
        ),
    ]
