# Generated by Django 4.2.20 on 2025-04-27 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceitem",
            name="earliest_availability",
            field=models.DateField(blank=True, null=True),
        ),
    ]
