# Generated by Django 4.2.20 on 2025-04-13 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='tabs',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='unavailable_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='view_type',
            field=models.CharField(default='card', max_length=50),
        ),
    ]
