# Generated by Django 4.2.20 on 2025-05-05 20:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="servicesignup",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="servicesignup",
                to="neighborly_services.serviceitem",
            ),
        ),
    ]
