# Generated by Django 4.2.20 on 2025-04-13 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0002_serviceitem_price_serviceitem_tabs_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
