# Generated by Django 4.2.20 on 2025-04-14 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0003_serviceitem_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='servicesignup',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RemoveField(
            model_name='servicesignup',
            name='user_id',
        ),
    ]
