# Generated by Django 4.2.20 on 2025-04-14 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0004_rename_service_id_servicesignup_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesignup',
            name='user_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
