# Generated by Django 4.2.20 on 2025-04-14 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0005_servicesignup_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicesignup',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesignup',
            name='messages',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesignup',
            name='price',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='servicesignup',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='servicesignup',
            name='status',
            field=models.CharField(default='pending', max_length=10),
        ),
    ]
