# Generated by Django 4.2.20 on 2025-04-17 21:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "neighborly_services",
            "0006_servicesignup_end_date_servicesignup_messages_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceitem",
            old_name="tabs",
            new_name="tags",
        ),
    ]
