# Generated by Django 4.2.20 on 2025-04-17 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_services", "0007_rename_tabs_serviceitem_tags"),
    ]

    operations = [
        migrations.RenameField(
            model_name="serviceitem",
            old_name="earliest_availability",
            new_name="closestAvailability",
        ),
    ]
