# Generated by Django 4.2.20 on 2025-04-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0008_rename_earliest_availability_serviceitem_closestavailability'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='quota',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
