# Generated by Django 4.2.20 on 2025-04-19 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0009_serviceitem_latitude_serviceitem_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
