# Generated by Django 4.2.20 on 2025-04-20 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0010_alter_serviceitem_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceitem',
            name='view_type',
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='visibility',
            field=models.CharField(default='public', max_length=10),
        ),
    ]
