# Generated by Django 4.2.20 on 2025-04-21 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0011_remove_serviceitem_view_type_serviceitem_visibility'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='address_line1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='neighborhood',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='zip_code',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
