# Generated by Django 4.2.20 on 2025-04-21 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0012_serviceitem_address_line1_serviceitem_city_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceitem',
            old_name='address_line1',
            new_name='street_address',
        ),
    ]
