# Generated by Django 4.2.20 on 2025-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_services', '0013_rename_address_line1_serviceitem_street_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
