# Generated by Django 4.2.20 on 2025-03-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("event_id", models.AutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=255)),
                ("organizer_name", models.CharField(max_length=255)),
                ("organizer_id", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("time", models.TimeField()),
                ("visibility", models.CharField(max_length=255)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("recurring", models.BooleanField(default=False)),
                ("max_attendees", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="EventSignUp",
            fields=[
                ("signup_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neighborly_events.event",
                    ),
                ),
            ],
        ),
    ]
