# Generated by Django 4.2.20 on 2025-04-15 22:15

from django.db import migrations, models
import neighborly_events.models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=neighborly_events.models.event_image_upload_path),
        ),
    ]
