# Generated by Django 4.2.20 on 2025-05-13 20:00

from django.db import migrations, models
import neighborly_users.models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="icon",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=neighborly_users.models.user_icon_upload_path,
            ),
        ),
    ]
