# Generated by Django 4.2.20 on 2025-04-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="is_superuser",
            field=models.BooleanField(
                default=False,
                help_text="Designates that this user has all permissions without explicitly assigning them.",
                verbose_name="superuser status",
            ),
        ),
    ]
