# Generated by Django 4.2.20 on 2025-04-14 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Petition",
            fields=[
                ("petition_id", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("organizer_id", models.CharField(max_length=255)),
                ("visibility", models.BooleanField(default=True)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("target", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="PetitionSignature",
            fields=[
                ("signature_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("signed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "petition",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="neighborly_petitions.petition",
                    ),
                ),
            ],
        ),
    ]
