# Generated by Django 5.2 on 2025-04-14 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_petitions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='petition',
            name='hero_image',
            field=models.URLField(default='https://source.unsplash.com/featured/?nature,protest', max_length=500),
        ),
        migrations.AddField(
            model_name='petition',
            name='location',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='petition',
            name='provider',
            field=models.CharField(default='Anonymous', max_length=100),
        ),
        migrations.AddField(
            model_name='petition',
            name='voting_ends_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
