# Generated by Django 4.2.20 on 2025-05-07 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_petitions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="petitionsignature",
            name="user_name",
            field=models.CharField(default="Anonymous User", max_length=255),
        ),
    ]
