# Generated by Django 4.2.20 on 2025-05-07 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_petitions", "0002_petitionsignature_user_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="neighborhood",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="street_address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="petition",
            name="zip_code",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="petition",
            name="location",
            field=models.CharField(max_length=255),
        ),
    ]
