# Generated by Django 4.2.20 on 2025-05-07 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "neighborly_petitions",
            "0003_petition_city_petition_latitude_petition_longitude_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="petition",
            name="visibility",
            field=models.CharField(default="public", max_length=10),
        ),
    ]
