# Generated by Django 4.2.20 on 2025-04-21 18:52

from django.db import migrations, models
import neighborly_verified_content.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UsersDocuments",
            fields=[
                ("ud_id", models.AutoField(primary_key=True, serialize=False)),
                ("user_id", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=255)),
                (
                    "file",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=neighborly_verified_content.models.documents_image_upload_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
