# Generated by Django 4.2.20 on 2025-04-21 23:12

from django.db import migrations, models
import neighborly_verified_content.models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_verified_content", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usersdocuments",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=neighborly_verified_content.models.documents_image_upload_path,
                validators=[neighborly_verified_content.models.validate_file_extension],
            ),
        ),
    ]
