# Generated by Django 4.2.20 on 2025-04-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_verified_content', '0002_alter_usersdocuments_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersdocuments',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
