# Generated by Django 4.2.20 on 2025-05-02 23:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tool',
            fields=[
                ('tool_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('owner_id', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('street_address', models.CharField(blank=True, max_length=255, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=100, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=20, null=True)),
                ('neighborhood', models.CharField(blank=True, max_length=100, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('available', models.BooleanField(default=True)),
                ('waitlist', models.JSONField(blank=True, default=list)),
                ('closestAvailability', models.DateField(blank=True, null=True)),
                ('unavailable_dates', models.JSONField(blank=True, default=list)),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quota', models.IntegerField(blank=True, default=0)),
                ('visibility', models.CharField(default='public', max_length=10)),
                ('tags', models.JSONField(blank=True, default=list)),
                ('images', models.JSONField(blank=True, default=list)),
                ('condition', models.CharField(choices=[('New', 'New'), ('Used', 'Used')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRequest',
            fields=[
                ('signup_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('messages', models.TextField(blank=True, null=True)),
                ('price', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='pending', max_length=10)),
                ('signed_at', models.DateTimeField(auto_now_add=True)),
                ('tool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='borrow_requests', to='neighborly_tools.tool')),
            ],
        ),
    ]
