# Generated by Django 4.2.20 on 2025-04-22 21:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tool",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("owner_id", models.CharField(max_length=255)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "condition",
                    models.CharField(
                        choices=[("New", "New"), ("Used", "Used")], max_length=50
                    ),
                ),
                ("availability", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="BorrowRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("borrow_date", models.DateField()),
                ("return_date", models.DateField()),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="borrow_requests",
                        to="neighborly_tools.tool",
                    ),
                ),
            ],
        ),
    ]
