# Generated by Django 4.2.20 on 2025-04-30 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tool',
            name='owner_id',
            field=models.CharField(max_length=255),
        ),
    ]
