# Generated by Django 4.2.20 on 2025-05-03 18:42

from django.db import migrations, models
import neighborly_tools.models


class Migration(migrations.Migration):

    dependencies = [
        ("neighborly_tools", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tool",
            name="condition",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Used", "Used"),
                    ("Like New", "Like New"),
                    ("Fair", "Fair"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="tool",
            name="images",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=neighborly_tools.models.tools_image_upload_path,
            ),
        ),
    ]
