# Generated by Django 4.2.20 on 2025-04-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighborly_tools', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrowrequest',
            name='signed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
